version: '3'

services:
  node:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'

  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
