version: '3'

services:
  node:
    container_name: barberapp1
    build:
      context: .
    env_file:
      - .env
    environment:
      - RUN_MIGRATIONS=true
    depends_on:
      - postgres
      - mongodb
      - redis
    volumes:
      - .:/app
    ports:
      - '3000:3000'

  postgres:
    container_name: barberdb
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - storage_app:/var/lib/postgresql/postgresdata
    networks:
      - backendnestjs

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: docker
    volumes:
      - storage_app:/var/lib/mongodb/mongodata
    networks:
      - backendnestjs

  redis:
    image: redis:6-alpine
    networks:
      - backendnestjs


networks:
  backendnestjs:
    driver: bridge

volumes:
  storage_app:
    driver: local
